
ALTER TABLE "тестовое"
ALTER COLUMN "RUNFACT" TYPE NUMERIC(10,2)
USING REPLACE("RUNFACT", ',', '.')::NUMERIC,
ALTER COLUMN "RUNPLAN" TYPE NUMERIC(10,2)
USING REPLACE("RUNPLAN", ',', '.')::NUMERIC

SELECT
  DATE("DATERELEASE") "DATERELEASE", "ROUTEID",
  COUNT(CASE WHEN "RUNPLAN" != 0 THEN 1 END) AS plan_trips_count,
  COUNT(CASE WHEN "RUNFACT" != 0 THEN 1 END) AS fact_trips_count,
  SUM("RUNPLAN") AS plan_distance,
  SUM("RUNFACT") AS fact_distance
FROM "тестовое"
GROUP BY 1, 2
ORDER BY 1, 2